[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#e5e5e5"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 14

[font.bold]
family = "JetBrainsMonoNL NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL NF"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMonoNL NF"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMonoNL NF"
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 5
y = 5
